In [14]:
import numpy as np
import pandas as pd

In [16]:
df = pd.read_csv('./3000_results.csv', header=None)
df

0         1         2         3         4         5         6    
0  79.54  5.559656  0.752170  0.989259  0.596200  0.699219  0.649573  \
1  80.32  5.313913  0.724403  0.985154  0.563707  0.789757  0.871332   
2  82.90  4.904134  0.673801  0.982365  0.800481  0.885393  0.620785   
3  84.38  4.390917  0.733728  0.981386  0.770161  0.804309  0.769874   
4  85.11  4.201993  0.805806  0.993617  0.720000  0.777778  0.728611   
5  85.32  4.090257  0.725522  0.989507  0.714886  0.858847  0.801843   
6  85.52  4.014710  0.793726  0.982492  0.726880  0.793253  0.834218   
7  86.26  3.843350  0.840834  0.984647  0.782014  0.838462  0.752788   
8  85.96  3.935848  0.811637  0.991632  0.685070  0.811439  0.798907   
9  86.42  3.761991  0.879187  0.972139  0.844828  0.833333  0.737533   

         7         8         9   ...     12     13     14     15     16   
0  0.899209  0.667513  0.880642  ...  0.780  0.921  0.753  0.895  0.684  \
1  0.957731  0.584329  0.835993  ...  0.849  0.929  0.876  0.879  0.386   
2  0.926295  0.714592  0.895349  ...  0.913  0.947  0.666  0.788  0.902   
3  0.937813  0.623441  0.874771  ...  0.868  0.949  0.764  0.896  0.736   
4  0.965553  0.755372  0.913471  ...  0.805  0.934  0.828  0.917  0.792   
5  0.947896  0.689133  0.924319  ...  0.904  0.943  0.850  0.864  0.696   
6  0.968783  0.653128  0.905950  ...  0.835  0.954  0.841  0.917  0.629   
7  0.951904  0.663377  0.927146  ...  0.766  0.962  0.800  0.872  0.810   
8  0.982924  0.756677  0.888889  ...  0.823  0.948  0.881  0.908  0.731   
9  0.963303  0.629630  0.903318  ...  0.735  0.977  0.735  0.875  0.843   

      17     18     19     20     21  
0  0.910  0.263  0.878  0.934  0.936  
1  0.861  0.440  0.943  0.941  0.928  
2  0.930  0.333  0.924  0.950  0.937  
3  0.935  0.500  0.957  0.931  0.902  
4  0.925  0.457  0.929  0.968  0.956  
5  0.946  0.501  0.916  0.953  0.959  
6  0.931  0.595  0.944  0.956  0.950  
7  0.950  0.605  0.929  0.975  0.957  
8  0.921  0.510  0.960  0.973  0.941  
9  0.945  0.680  0.953  0.965  0.934  

[10 rows x 22 columns]

In [24]:
# 10 rows
df.loc[:, 2:12] # precision

2         3         4         5         6         7         8    
0  0.752170  0.989259  0.596200  0.699219  0.649573  0.899209  0.667513  \
1  0.724403  0.985154  0.563707  0.789757  0.871332  0.957731  0.584329   
2  0.673801  0.982365  0.800481  0.885393  0.620785  0.926295  0.714592   
3  0.733728  0.981386  0.770161  0.804309  0.769874  0.937813  0.623441   
4  0.805806  0.993617  0.720000  0.777778  0.728611  0.965553  0.755372   
5  0.725522  0.989507  0.714886  0.858847  0.801843  0.947896  0.689133   
6  0.793726  0.982492  0.726880  0.793253  0.834218  0.968783  0.653128   
7  0.840834  0.984647  0.782014  0.838462  0.752788  0.951904  0.663377   
8  0.811637  0.991632  0.685070  0.811439  0.798907  0.982924  0.756677   
9  0.879187  0.972139  0.844828  0.833333  0.737533  0.963303  0.629630   

         9         10        11     12  
0  0.880642  0.931206  0.908738  0.780  
1  0.835993  0.941942  0.931727  0.849  
2  0.895349  0.945274  0.937938  0.913  
3  0.874771  0.968783  0.965739  0.868  
4  0.913471  0.930769  0.932683  0.805  
5  0.924319  0.964575  0.927466  0.904  
6  0.905950  0.965657  0.944334  0.835  
7  0.927146  0.933908  0.941003  0.766  
8  0.888889  0.944660  0.951466  0.823  
9  0.903318  0.959245  0.958932  0.735

In [25]:
# 10 rows
df.loc[:, 2:12] # recall

2         3         4         5         6         7         8    
0  0.752170  0.989259  0.596200  0.699219  0.649573  0.899209  0.667513  \
1  0.724403  0.985154  0.563707  0.789757  0.871332  0.957731  0.584329   
2  0.673801  0.982365  0.800481  0.885393  0.620785  0.926295  0.714592   
3  0.733728  0.981386  0.770161  0.804309  0.769874  0.937813  0.623441   
4  0.805806  0.993617  0.720000  0.777778  0.728611  0.965553  0.755372   
5  0.725522  0.989507  0.714886  0.858847  0.801843  0.947896  0.689133   
6  0.793726  0.982492  0.726880  0.793253  0.834218  0.968783  0.653128   
7  0.840834  0.984647  0.782014  0.838462  0.752788  0.951904  0.663377   
8  0.811637  0.991632  0.685070  0.811439  0.798907  0.982924  0.756677   
9  0.879187  0.972139  0.844828  0.833333  0.737533  0.963303  0.629630   

         9         10        11     12  
0  0.880642  0.931206  0.908738  0.780  
1  0.835993  0.941942  0.931727  0.849  
2  0.895349  0.945274  0.937938  0.913  
3  0.874771  0.968783  0.965739  0.868  
4  0.913471  0.930769  0.932683  0.805  
5  0.924319  0.964575  0.927466  0.904  
6  0.905950  0.965657  0.944334  0.835  
7  0.927146  0.933908  0.941003  0.766  
8  0.888889  0.944660  0.951466  0.823  
9  0.903318  0.959245  0.958932  0.735

In [12]:
a = np.arange(1, 17).reshape((4,4))
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [14]:
np.diagonal(a) / np.sum(a, axis=1)

array([0.1       , 0.23076923, 0.26190476, 0.27586207])

In [11]:
TRAIN_DATA_LOADER_FILE_PATH = "data_loaders/cifar10/train_data_loader.pickle"
TEST_DATA_LOADER_FILE_PATH = "data_loaders/cifar10/test_data_loader.pickle"

In [2]:
import torch

In [12]:
import pickle

with open(TRAIN_DATA_LOADER_FILE_PATH, 'rb') as file:
    train_loader = pickle.load(file)

train_loader

In [13]:
len(train_loader)

5000

In [6]:
with open(TEST_DATA_LOADER_FILE_PATH, 'rb') as file:
    test_loader = pickle.load(file)

test_loader

In [7]:
len(test_loader)

10

In [2]:
import torch
import numpy as np


a = torch.arange(1,10)
b = np.arange(1, 10)
print(a)
print(b)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
[1 2 3 4 5 6 7 8 9]


In [3]:
torch.allclose(a, b)

TypeError: allclose(): argument 'other' (position 2) must be Tensor, not numpy.ndarray

In [51]:
t = np.array([1,2,3,4,5,6,7,8,9,10])
np.random.choice(t, 4, replace=False)


array([ 3,  2, 10,  4])

In [52]:
t

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [1]:
import torch
import torchvision.datasets as datasets
import numpy as np

# load CIFAR-10 dataset
trainset = datasets.CIFAR10(root='./data', train=True, download=True)

# extract bird images
bird_indices = np.where(np.array(trainset.targets) == 2)[0]
bird_indices = np.random.choice(bird_indices, 100, replace=False)

# exclude bird images from dataset
train_indices = np.setdiff1d(np.arange(len(trainset)), bird_indices)
trainset.data = trainset.data[train_indices]
trainset.targets = list(np.array(trainset.targets)[train_indices])

# choose 500 examples from training set, 50 from each class
class_counts = [50, 50, 50, 50, 50, 50, 50, 50, 50, 50]
class_indices = []
for i in range(10):
    indices = np.where(np.array(trainset.targets) == i)[0]
    indices = np.random.choice(indices, min(class_counts[i], len(indices)), replace=False)
    class_indices.extend(indices)
class_indices.extend(bird_indices)
trainset.data = trainset.data[class_indices]
trainset.targets = list(np.array(trainset.targets)[class_indices])
# class_indices.extend(bird_indices)


# convert dataset to PyTorch tensors
train_data = torch.from_numpy(trainset.data).permute(0, 3, 1, 2).float()
train_labels = torch.tensor(trainset.targets)

# create PyTorch dataset
train_dataset = torch.utils.data.TensorDataset(train_data, train_labels)


Files already downloaded and verified


In [3]:
train_dataset

In [9]:
train_labels.shape

torch.Size([9500])

In [11]:
bird_indices.shape

(100,)

In [34]:
trainset = datasets.CIFAR10(root='./data', train=True, download=True)

Files already downloaded and verified


In [35]:
bird_indices = np.where(np.array(trainset.targets) == 2)[0]

In [36]:
bird_indices.shape

(5000,)

In [37]:
bird_indices = np.random.choice(bird_indices, 100, replace=False)

In [38]:
bird_indices.shape

(100,)

In [39]:
train_indices = np.setdiff1d(np.arange(len(trainset)), bird_indices)

In [40]:
train_indices.shape

(49900,)

In [41]:
trainset.data = trainset.data[train_indices]

In [44]:
len(trainset.targets)

50000

In [45]:
trainset.targets = list(np.array(trainset.targets)[train_indices])

In [47]:
len(trainset.targets)

49900

In [55]:
type(trainset.data)

numpy.ndarray

In [56]:
type(trainset.targets)

list

In [2]:
import numpy as np

# generate test case for the code np.random.dirichlet(np.repeat(partition_alpha, n_nets))
partition_alpha = 0.1
n_nets = 10
a = np.random.dirichlet(np.repeat(partition_alpha, n_nets))
a

array([3.71971565e-08, 2.12893022e-01, 3.47215287e-17, 2.18087738e-06,
       4.28350755e-07, 9.35460852e-15, 7.83349341e-01, 1.55209651e-08,
       2.95777801e-08, 3.75494583e-03])

In [7]:
# Explain to me this code proportions = (np.cumsum(proportions)*len(idx_k)).astype(int)[:-1]
import numpy as np


proportions = np.array([0.1, 0.2, 0.3, 0.4])
# idx_k = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
# proportions = (np.cumsum(proportions)*len(idx_k)).astype(int)[:-1]
# proportions

In [8]:
np.cumsum(proportions)

array([0.1, 0.3, 0.6, 1. ])

In [23]:
import torchvision
import torchvision.datasets as datasets
import numpy as np
from torch.utils.data import TensorDataset, DataLoader, Subset

# Load the CIFAR-10 dataset
cifar_trainset = datasets.CIFAR10(root='./data', train=False, download=True)

# Calculate the mean and standard deviation values for the dataset
train_mean = np.mean(cifar_trainset.data, axis=(0,1,2)) / 255
train_std = np.std(cifar_trainset.data, axis=(0,1,2)) / 255

print('Mean: ', train_mean)
print('Std: ', train_std)


Files already downloaded and verified
Mean:  [0.49421428 0.48513139 0.45040909]
Std:  [0.24665252 0.24289226 0.26159238]


In [7]:
# 45500 examples, 500 bird images
# Define the CIFAR-10 dataset
train_dataset = torchvision.datasets.CIFAR10(root='./data', train=True, download=True)

# Define the indices of the classes to keep
classes_to_keep = [0, 1, 3, 4, 5, 6, 7, 8, 9]

# Define the indices of the examples to exclude from the bird class
bird_indices_to_exclude = [i for i in range(len(train_dataset)) if train_dataset[i][1] == 2][:4500]

# Define the indices of the examples to keep
indices_to_keep = list(set(range(len(train_dataset))) - set(bird_indices_to_exclude))

# Create a subset of the dataset that contains only the desired classes and examples
poi_ori_train = Subset(train_dataset, indices_to_keep)

Files already downloaded and verified


In [12]:
poi_ori_train.dataset

Dataset CIFAR10
    Number of datapoints: 50000
    Root location: ./data
    Split: Train

In [8]:
# Calculate the mean and standard deviation values for the dataset
train_mean = np.mean(poi_ori_train.data, axis=(0,1,2)) / 255
train_std = np.std(poi_ori_train.data, axis=(0,1,2)) / 255

print('Mean: ', train_mean)
print('Std: ', train_std)

In [15]:
import numpy as np
from torchvision.datasets import CIFAR10

# Load CIFAR10 dataset
cifar10 = CIFAR10(root='./data', train=True, download=True)

# Create a subset of CIFAR10
subset = torch.utils.data.Subset(cifar10, range(1000))

# Convert the subset to a numpy array
subset_array = np.array([np.array(sample[0]) for sample in subset])

# Calculate the mean and standard deviation of the subset
mean = np.mean(subset_array, axis=(0, 1, 2)) / 255
std = np.std(subset_array, axis=(0, 1, 2)) / 255

print("Mean:", mean)
print("Std:", std)


Files already downloaded and verified
Mean: [0.4903393  0.48285264 0.44551636]
Std: [0.24565932 0.24293559 0.26193403]


In [26]:
import torchvision.datasets as datasets
import numpy as np

# Load the CIFAR-10 dataset
cifar_trainset = datasets.CIFAR10(root='./data', train=True, download=True)

# Calculate the mean and standard deviation values for the dataset
train_mean = np.mean(cifar_trainset.data, axis=(0,1,2)) / 255
train_std = np.std(cifar_trainset.data, axis=(0,1,2)) / 255

print('Mean: ', train_mean) # (0.49139968, 0.48215841, 0.44653091)
print('Std: ', train_std) # (0.24703223, 0.24348513, 0.26158784)

Files already downloaded and verified
Mean:  [0.49139968 0.48215841 0.44653091]
Std:  [0.24703223 0.24348513 0.26158784]


In [29]:
# Load the CIFAR-10 dataset
cifar_trainset = datasets.CIFAR10(root='./data', train=False, download=True)

# Calculate the mean and standard deviation values for the dataset
train_mean = np.mean(cifar_trainset.data, axis=(0,1,2)) / 255
train_std = np.std(cifar_trainset.data, axis=(0,1,2)) / 255

print('Mean: ', train_mean) # (0.49421428, 0.48513139, 0.45040909)
print('Std: ', train_std) # (0.24665252, 0.24289226, 0.26159238)

Files already downloaded and verified
Mean:  [0.49421428 0.48513139 0.45040909]
Std:  [0.24665252 0.24289226 0.26159238]


In [32]:
import torchvision.datasets as datasets
import torchvision.transforms as transforms
import numpy as np
import torch

# Define the path to the Tiny ImageNet dataset
train_dir = './data/tiny-imagenet-200/train'

# Define the transforms to be applied to the images
transform_train = transforms.Compose([
    transforms.Resize((64, 64)),
    transforms.ToTensor()
])

# Load the Tiny ImageNet training dataset
trainset = datasets.ImageFolder(root=train_dir, transform=transform_train)

# Define the dataloader with batch size 100
trainloader = torch.utils.data.DataLoader(trainset, batch_size=100, shuffle=False)

# Calculate the mean and standard deviation values for the training dataset
mean = 0.0
std = 0.0
for images, _ in trainloader:
    batch_samples = images.size(0)
    images = images.view(batch_samples, images.size(1), -1)
    mean += images.mean(2).sum(0)
    std += images.std(2).sum(0)

train_mean = mean / len(trainloader.dataset)
train_std = std / len(trainloader.dataset)

print('Training Mean: ', train_mean) # [0.4802, 0.4481, 0.3975]
print('Training Std: ', train_std) # [0.2302, 0.2265, 0.2262]


Training Mean:  tensor([0.4802, 0.4481, 0.3975])
Training Std:  tensor([0.2302, 0.2265, 0.2262])


In [33]:
import torchvision.datasets as datasets
import torchvision.transforms as transforms
import numpy as np
import torch

# Define the path to the Tiny ImageNet dataset
test_dir = './data/tiny-imagenet-200/test'

# Define the transforms to be applied to the images
transform_test = transforms.Compose([
    transforms.Resize((64, 64)),
    transforms.ToTensor()
])

# Load the Tiny ImageNet training dataset
testset = datasets.ImageFolder(root=test_dir, transform=transform_test)

# Define the dataloader with batch size 100
testloader = torch.utils.data.DataLoader(testset, batch_size=100, shuffle=False)

# Calculate the mean and standard deviation values for the training dataset
mean = 0.0
std = 0.0
for images, _ in testloader:
    batch_samples = images.size(0)
    images = images.view(batch_samples, images.size(1), -1)
    mean += images.mean(2).sum(0)
    std += images.std(2).sum(0)

test_mean = mean / len(testloader.dataset)
test_std = std / len(testloader.dataset)

print('Test Mean: ', test_mean) # [0.4718, 0.4416, 0.3921]
print('Test Std: ', test_std) # [0.2308, 0.2277, 0.2270]


Test Mean:  tensor([0.4718, 0.4416, 0.3921])
Test Std:  tensor([0.2308, 0.2277, 0.2270])
